[package]
name = "sparseio"
authors = ["Matthew Hambrecht (hambrechtmatt@gmail.com)"]
version = "0.0.1"
edition = "2024"
description = "A library for coordinating sparse, out-of-order byte-range fetching and materialization of large objects."
documentation = "https://docs.rs/sparseio"
homepage = "https://crates.io/crates/sparseio"
repository = "https://github.com/mhambre/sparseio"
categories = ["filesystem"]
keywords = ["storage", "tokio", "fs", "filesystem", "stream"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
parking_lot = "0.12"
bytes = "1.11"
futures-timer = "3.0"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "time"] }
