name: Integration Tests

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:
    name: ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-${{ inputs.runner }}

      - name: Core integration tests
        run: cargo nextest run --lib core --features test-utils

      - name: Harness implementation integration tests
        run: cargo nextest run --lib harness --features debug

      - name: File implementation integration tests
        run: cargo nextest run --lib file --features test-utils,impl-file

      - name: OpenDAL implementation integration tests
        run: cargo nextest run --lib opendal --features test-utils,impl-opendal