name: Quality and Compilation Checks

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality:
    name: ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargo-${{ inputs.runner }}

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --profile minimal --component rustfmt

      - name: Rustfmt
        run: |
          cargo +nightly fmt --all -- --check
          
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      - name: Feature compile checks
        run: |
          cargo hack check --each-feature
          cargo hack check --no-default-features

      - name: Docs.rs feature set
        run: RUSTDOCFLAGS='--cfg docsrs' cargo doc --all-features --no-deps
